@startuml

file dot.exe
component gvc.dll
component gvplugin_dot_layout.dll
component libexpat.dll
component gvplugin_core.dll
component vcruntime140.dll
component cgraph.dll
component pathplan.dll
component xdot.dll
component cdt.dll
component zlib1.dll
file config6

dot.exe --> gvc.dll
dot.exe --> cgraph.dll
dot.exe --> vcruntime140.dll

gvc.dll --> cgraph.dll
gvc.dll --> pathplan.dll
gvc.dll --> xdot.dll
gvc.dll --> libexpat.dll
gvc.dll --> zlib1.dll
gvc.dll --> cdt.dll
gvc.dll --> vcruntime140.dll
gvc.dll ..> config6 : loads plugins


cgraph.dll --> cdt.dll
cgraph.dll --> vcruntime140.dll

libexpat.dll --> vcruntime140.dll

pathplan.dll --> vcruntime140.dll

xdot.dll --> vcruntime140.dll
cdt.dll --> vcruntime140.dll

gvplugin_core.dll --> gvc.dll
gvplugin_core.dll --> cgraph.dll
gvplugin_core.dll --> cdt.dll
gvplugin_core.dll --> xdot.dll
gvplugin_core.dll --> vcruntime140.dll
config6 ..> gvplugin_core.dll : core plugin

gvplugin_dot_layout.dll --> gvc.dll
gvplugin_dot_layout.dll --> cgraph.dll
gvplugin_dot_layout.dll --> cdt.dll
gvplugin_dot_layout.dll --> vcruntime140.dll
config6 ..> gvplugin_dot_layout.dll : dot plugin

zlib1.dll --> vcruntime140.dll

@enduml